name: Deploy Docker Image

on:
  push:
    branches:
      - main  # Выполняется только при пуше в main (измените при необходимости)

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}  # Имя образа в GitHub Container Registry
  IMAGE_TAG: ${{ github.sha }}  # Тэг образа (использует SHA коммита)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:${{ env.IMAGE_TAG }} .
          docker tag $IMAGE_NAME:${{ env.IMAGE_TAG }} $IMAGE_NAME:latest

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push $IMAGE_NAME:${{ env.IMAGE_TAG }}
          docker push $IMAGE_NAME:latest

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull $IMAGE_NAME:latest
            docker stop web_rolgang || true
            docker rm web_rolgang || true
            docker run -d --name web_rolgang $IMAGE_NAME:latest
